import pandas as pd
from ODBC.BPCSquery import BPCSquery

query = """
SELECT IIM.IPROD,IIM.IDESC,IIM.IVEND,IIM.ISCST,IIM.ILIST,IIX.IXRATG,ICX.CXPPLC,COALESCE(STKOH.SUM_STKOH, 0) AS STKOH01,ISCST*COALESCE(STKOH.SUM_STKOH, 0) AS STKVALUE
FROM IIML01 IIM
INNER JOIN ICXL01 ICX
ON IIM.ICLAS = ICX.CXCLAS
LEFT JOIN 
    (
        SELECT 
            WPROD, 
            SUM(WOPB + WRCT - WISS + WADJ) AS SUM_STKOH
        FROM 
            IWIL01
        WHERE 
            WPROD NOT LIKE 'FA%' 
        GROUP BY 
            WPROD
    ) STKOH 
ON 
    IIM.IPROD = STKOH.WPROD
LEFT JOIN IIXL01 IIX
ON
IIM.IPROD=IIX.IXITMN
WHERE 
    IPROD NOT LIKE 'FA%'
    AND IVEND >102
    AND CXPPLC != 'APE'
"""

df = BPCSquery(query,"JPNPRDF")
print(df)

