库存

SELECT WPROD, WMIN, WWHS, SUM(WOPB + WRCT - WISS + WADJ) AS STKOH 
FROM IWIL01 
WHERE WPROD NOT LIKE 'FA%' 
  AND WWHS = '5' 
GROUP BY WPROD, WMIN, WWHS
HAVING SUM(WOPB + WRCT - WISS + WADJ) > 0


ITEMMASTER

SELECT IPROD,IDESC,ICLAS,IVEND,ISCST,ILIST,CXPPLC
FROM IIML01 A
LEFT JOIN ICXL01 B
ON A.ICLAS = B.CXCLAS

JPNPOBYRT

SELECT HPO.PVEND,AVM.VNDNAM,HPO.PEDTE,HPO.PORD,HPO.PLINE,IIM.IPROD,IIM.IDESC,HPO.PQORD,HPO.PECST,HPO.POCUR,HPO.PDDTE,HPO.HVDUE,HPO.PCMT,IIM.ILOC,IWI.WLEAD,IWI.WLOTS,IWI.WILOC
FROM HPOL01 HPO
INNER JOIN IIML01 IIM
ON HPO.PPROD = IIM.IPROD
INNER JOIN AVML01 AVM
ON HPO.PVEND=AVM.VENDOR
LEFT JOIN IWIL01 IWI
ON IIM.IPROD=IWI.WPROD
WHERE HPO.PEDTE > 20231101
AND HPO.PWHSE IN ('A1','5','6')
AND IIM.IPROD NOT LIKE 'FA%'
AND HPO.PVEND > 10000
AND HPO.PCMT !='TO BE DELETED'
AND IWI.WWHS = '5'

CUSTLIST

SELECT RCK.RKCUST,RCK.RKNAME,RCK.RKFIL2,RCM.CNME,RCK.RKADD1,RCK.RKADD2,RCK.RKADD3,RCM.CZIP,RCM.CPHON,RCX.CXFAX,RCM.CRDOL,RCX.CXGIND,RCM.CTERM,RCM.CMSIC,RCM.CTYPE,RCM.CTAX,RCM.CWHSE
FROM JPNLOCF.RCMKL01 RCK
INNER JOIN JPNPRDF.RCML01 RCM
ON RCK.RKCUST=RCM.CCUST
INNER JOIN JPNPRDF.RCXL01 RCX
ON RCK.RKCUST=RCX.CXCUSN

SGWORDER

SELECT ECL.LODTE,ECL.LORD,ECH.HCPO,ECL.LLINE,ECL.LPROD,IIM.IDESC,ECL.LQORD,ECL.LQALL,ECL.LQSHP,ECL.LNET,ECL.LRDTE,ECL.LSDTE,ECL.LLOC,IIM.IVEND,AVM.VNDNAM
FROM ECL ECL
INNER JOIN ECHL01 ECH ON ECL.LORD=ECH.HORD
INNER JOIN IIML01 IIM ON ECL.LPROD=IIM.IPROD
INNER JOIN AVML01 AVM ON IIM.IVEND=AVM.VENDOR
WHERE ECH.HCUST=9125
AND ECL.LSTAT = 'E'
AND ECH.HEDTE > 20231101
AND ECL.LQORD > 0